-- ********** TABELA DISCIPLINA ********** --

create table disciplina (
cod text, 
nome text, 
cred int, 
cod_tipo text);

-- Disciplinas obrigatórias
INSERT INTO disciplina (cod, nome, cred, cod_tipo)
VALUES 
       ('DCC003', 'ALGORITMOS E ESTRUTURA DE DADOS I', 4, 'OBG'),
       ('EEE001', 'INTRODUÇÃO À ENGENHARIA ELÉTRICA', 1, 'OBG'),
       ('EEE021', 'INTRODUÇÃO AO PROJETO DE ENGENHARIA', 2, 'OBG'),
       ('FIS054', 'INTRODUÇÃO À FÍSICA EXPERIMENTAL', 3, 'OBG'),
       ('MAT001', 'CÁLCULO DIFERENCIAL E INTEGRAL I', 6, 'OBG'),
       ('MAT038', 'GEOMETRIA ANALÍTICA E ÁLGEBRA LINEAR', 4, 'OBG'),
       ('DCC004', 'ALGORITMOS E ESTRUTURA DE DADOS II', 4, 'OBG'),
       ('DCC033', 'ANÁLISE NUMÉRICA', 4, 'OBG'),
       ('FIS060', 'FÍSICA EXPERIMENTAL EO', 3, 'OBG'),
       ('FIS065', 'FUNDAMENTOS DE MECÂNICA', 4, 'OBG'),
       ('FIS066', 'FUNDAMENTOS DE TERMODINÂMICA', 2, 'OBG'),
       ('MAT039', 'CÁLCULO DIFERENCIAL E INTEGRAL II', 4, 'OBG'),
       ('ELE064', 'ANÁLISE DE CIRCUITOS ELÉTRICOS I', 2, 'OBG'),
       ('ELT083', 'SISTEMAS DIGITAIS', 3, 'OBG'),
       ('EQM044', 'FENÔMENOS DE TRANSPORTE', 3, 'OBG'),
       ('FIS069', 'FUNDAMENTOS DE ELETROMAGNETISMO', 4, 'OBG'),
       ('MAT002', 'CÁLCULO DIFERENCIAL E INTEGRAL III', 4, 'OBG'),
       ('MAT015', 'EQUAÇÕES DIFERENCIAIS A', 4, 'OBG'),
       ('ELE028', 'LABORATÓRIO DE CIRCUITOS ELÉTRICOS I', 2, 'OBG'),
       ('ELE065', 'ANÁLISE DE CIRCUITOS ELÉTRICOS II', 2, 'OBG'),
       ('ELT029', 'LABORATÓRIO DE SISTEMAS DIGITAIS', 2, 'OBG'),
       ('ELT032', 'ANÁLISE DE SISTEMAS LINEARES', 4, 'OBG'),
       ('EST045', 'PROBABILIDADE E PROCESSOS ESTOCÁSTICOS', 4, 'OBG'),
       ('FIS086', 'FUNDAMENTOS DE OSCILAÇÕES, ONDAS E ÓPTICA', 4, 'OBG'),
       ('MAT016', 'EQUAÇÕES DIFERENCIAIS B', 4, 'OBG'),
       ('ELE001', 'ELETROMAGNETISMO', 4, 'OBG'),
       ('ELE031', 'LABORATÓRIO DE CIRCUITOS ELÉTRICOS II', 2, 'OBG'),
       ('ELE066', 'ANÁLISE DE CIRCUITOS ELÉTRICOS III', 2, 'OBG'),
       ('ELT005', 'SISTEMAS PROCESSADORES E PERIFÉRICOS', 5, 'OBG'),
       ('ELT035', 'CONTROLE DE SISTEMAS LINEARES', 4, 'OBG'),
       ('ELT084', 'DISPOSITIVOS E CIRCUITOS ELETRÔNICOS BÁSICOS', 4, 'OBG'),
       ('FIS088', 'FUNDAMENTOS DE FÍSICA QUÂNTICA', 2, 'OBG'),
       ('ELE029', 'SISTEMAS DE MEDIÇÃO', 4, 'OBG'),
       ('ELE032', 'TEORIA DOS MATERIAIS', 4, 'OBG'),
       ('ELE033', 'CIRCUITOS POLIFÁSICOS E MAGNÉTICOS', 4, 'OBG'),
       ('ELE034', 'CONVERSÃO DA ENERGIA', 4, 'OBG'),
       ('ELT089', 'LABORATÓRIO DE CIRCUITOS ELETRÔNICOS I', 2, 'OBG'),
       ('ELT085', 'CIRCUITOS ELETRÔNICOS ANALÓGICOS', 4, 'OBG'),
       ('ELT086', 'TEORIA DAS COMUNICAÇÕES', 3, 'OBG'),
       ('ELE035', 'LABORATÓRIO DE CONVERSÃO DA ENERGIA', 2, 'OBG'),
       ('ELE042', 'PROCESSAMENTO DE SINAIS', 4, 'OBG'),
       ('ELT090', 'LABORATÓRIO DE CIRCUITOS ELETRÔNICOS II', 2, 'OBG'),
       ('ELT087', 'LABORATÓRIO DE TELECOMUNICAÇÕES', 2, 'OBG'),
       ('EEE023', 'TRABALHO DE CONCLUSÃO DE CURSO I', 2, 'OBG'),
       ('EEE024', 'TRABALHO DE CONCLUSÃO DE CURSO II', 4, 'OBG'),
       ('EEE044', 'ESTÁGIO CURRICULAR ',13, 'OBG');
     
-- Disciplinas Formação em Ciências Humanas
INSERT INTO disciplina (cod, nome, cred, cod_tipo)
VALUES ('COM089', 'Comunicação e Movimentos Sociais', 4, 'FCH'),
       ('COM090', 'O Discurso Midiático e a Vida Social', 4, 'FCH'),
       ('DCP021', 'Introdução à Teoria Democrática', 4, 'FCH'),
       ('DCP023', 'Estado Moderno e Capitalismo', 4, 'FCH'),
       ('FIL028', 'Introdução à Filosofia: Ética', 4, 'FCH'),
       ('FIL029', 'Introdução à Filosofia: Filosofia da Ciência e Epistemologia', 4, 'FCH'),
       ('HIS039', 'Introdução à História da Cultura', 4, 'FCH'),
       ('HIS040', 'Tópicos em História do Brasil: História, Industrialização e Urbanização no Brasil', 4, 'FCH'),
       ('HIS239', 'Tópicos em História da Ciência: Introdução à Historiografia da Ciência', 4, 'FCH'),
       ('SOA046', 'Abordagens Temáticas em Sociologia: Globalização, Meio Ambiente e Engenharia', 4, 'FCH'),
       ('SOA048', 'Fundamentos de Análise Sociológica', 4, 'FCH'),
       ('SOA050', 'Modernidade e Mudança Social', 4, 'FCH');

-- Disciplinas Optativas
INSERT INTO disciplina (cod, nome, cred, cod_tipo)
VALUES ('DCC008', 'Software Básico', 4, 'OPT'),
       ('DCC010', 'Compiladores', 4, 'OPT'),
       ('DCC011', 'Introdução à Banco de Dados', 4, 'OPT'),
       ('DCC038', 'Programação Orientada a Objetos', 4, 'OPT'),
       ('DCC017', 'Introdução à Arquitetura de Computadores', 4, 'OPT'),
       ('DCC024', 'Linguagens de Programação', 4, 'OPT'),
       ('DCC129', 'Fundamentos da Teoria da Computação', 4, 'OPT'),
       ('DCC603', 'Engenharia de Software', 4, 'OPT'),
       ('DCC605', 'Sistemas Operacionais', 4, 'OPT'),
       ('EEEx01', 'Fundamentos de Energia Alternativa', 2, 'OPT'),
       ('EEEx02', 'Instrumentação Biomédica', 4, 'OPT'),
       ('EEEx03', 'Projeto de Sistemas Embutidos', 4, 'OPT'),
       ('EEEx04', 'Projetos de Sistemas VLSI', 4, 'OPT'),
       ('EEEx05', 'Redes Neurais Artificiais', 2, 'OPT'),
       ('EEEx06', 'Sistemas Especialistas', 2, 'OPT'),
       ('EEEx07', 'Sistemas Nebulosos', 2, 'OPT'),
       ('EEEx08', 'Tópicos em Computação A', 2, 'OPT'),
       ('EEEx09', 'Tópicos em Computação B', 3, 'OPT'),
       ('EEEx10', 'Tópicos em Computação C', 4, 'OPT'),
       ('EEEx11', 'Tópicos em Controle de Processos A', 2, 'OPT'),
       ('EEEx12', 'Tópicos em Controle de Processos B', 3, 'OPT'),
       ('EEEx13', 'Tópicos em Controle de Processos C', 4, 'OPT'),
       ('EEEx14', 'Tópicos em Eletrônica de Potência A', 2, 'OPT'),
       ('EEEx15', 'Tópicos em Eletrônica de Potência B', 3, 'OPT'),
       ('EEEx16', 'Tópicos em Eletrônica de Potência C', 4, 'OPT'),
       ('EEEx17', 'Tópicos em Sistemas de Energia Elétrica A', 2, 'OPT'),
       ('EEEx18', 'Tópicos em Sistemas de Energia Elétrica B', 3, 'OPT'),
       ('EEEx19', 'Tópicos em Sistemas de Energia Elétrica C', 4, 'OPT'),
       ('EEEx20', 'Tópicos em Telecomunicações A', 2, 'OPT'),
       ('EEEx21', 'Tópicos em Telecomunicações B', 3, 'OPT'),
       ('EEEx22', 'Tópicos em Telecomunicações C', 4, 'OPT'),
       ('EEE004', 'Interfaces para Microcomputadores', 4, 'OPT'),
       ('EEE006', 'Tecnologia de Dispositivos Semicondutores', 4, 'OPT'),
       ('EEE007', 'Tópicos em Engenharia Elétrica A', 2, 'OPT'),
       ('EEE008', 'Tópicos em Engenharia Elétrica B', 3, 'OPT'),
       ('EEE009', 'Tópicos em Engenharia Elétrica C', 4, 'OPT'),
       ('EHD002', 'Máquinas Hidráulicas', 4, 'OPT'),
       ('EHD003', 'Usinas Hidroelétricas', 4, 'OPT'),
       ('ELEx23', 'Descargas Atmosféricas e Proteção Elétrica', 4, 'OPT'),
       ('ELE002', 'Aterramentos Elétricos', 4, 'OPT'),
       ('ELE036', 'Aplicações de Processamento Paralelo', 3, 'OPT'),
       ('ELE037', 'Otimização', 4, 'OPT'),
       ('ELE038', 'Projeto Assistido por Computador', 4, 'OPT'),
       ('ELE039', 'Acionamentos Elétricos', 4, 'OPT'),
       ('ELE040', 'Laboratório de Acionamentos Elétricos', 3, 'OPT'),
       ('ELE041', 'Manipuladores Robóticos', 4, 'OPT'),
       ('ELE043', 'Compatibilidade Eletromagnética', 4, 'OPT'),
       ('ELE044', 'Conservação de Energia', 3, 'OPT'),
       ('ELE045', 'Geração de Energia Elétrica', 4, 'OPT'),
       ('ELE046', 'Qualidade da Energia Elétrica', 3, 'OPT'),
       ('ELE047', 'Tecnologia de Máquinas Elétricas', 4, 'OPT'),
       ('ELE048', 'Veículos Elétricos e Híbridos', 3, 'OPT'),
       ('ELE049', 'Análise de Sistemas Elétricos de Potência', 4, 'OPT'),
       ('ELE050', 'Transitórios em Sistemas de Energia Elétrica', 4, 'OPT'),
       ('ELE051', 'Automação de Sistemas Elétricos de Potência', 3, 'OPT'),
       ('ELE052', 'Coordenação de Isolamento', 3, 'OPT'),
       ('ELE053', 'Estabilidade de Sistemas de Energia Elétrica', 3, 'OPT'),
       ('ELE054', 'Instalações Elétricas Residenciais e Prediais', 4, 'OPT'),
       ('ELE055', 'Planejamento de Sistemas de Energia Elétrica', 3, 'OPT'),
       ('ELE056', 'Proteção Digital de Sistemas Elétricos', 4, 'OPT'),
       ('ELE057', 'Supervisão e Controle de Sistemas de Energia Elétrica', 3, 'OPT'),
       ('ELE058', 'Campos e Ondas', 3, 'OPT'),
       ('ELE059', 'Fundamentos de Engenharia Biomédica', 4, 'OPT'),
       ('ELE061', 'Desenho Técnico', 4, 'OPT'),
       ('ELE062', 'Distribuição de Energia Elétrica', 3, 'OPT'),
       ('ELE614', 'Técnicas de Alta Tensão', 3, 'OPT'),
       ('ELE618', 'Sistemas Elétricos Industriais', 4, 'OPT'),
       ('ELTx24', 'Redes TCP/IP', 4, 'OPT'),
       ('ELT008', 'Informática Industrial', 4, 'OPT'),
       ('ELT010', 'Instrumentação Industrial', 3, 'OPT'),
       ('ELT011', 'Sistemas Distribuídos para Automação', 2, 'OPT'),
       ('ELT012', 'Automação em Tempo Real', 3, 'OPT'),
       ('ELT013', 'Controle Digital', 4, 'OPT'),
       ('ELT014', 'Laboratório de Controle e Automação I', 4, 'OPT'),
       ('ELT015', 'Laboratório de Controle e Automação II', 4, 'OPT'),
       ('ELT016', 'Técnicas de Modelagem de Sistemas Dinâmicos', 2, 'OPT'),
       ('ELT017', 'Controle Estocástico de Processos', 2, 'OPT'),
       ('ELT018', 'Introdução ao Controle Adaptativo', 2, 'OPT'),
       ('ELT019', 'Controle Multivariável', 2, 'OPT'),
       ('ELT036', 'Fundamentos de Redes de Comunicação', 4, 'OPT'),
       ('ELT037', 'Multimídia', 3, 'OPT'),
       ('ELT039', 'Técnicas de Controle de Processos Industriais', 3, 'OPT'),
       ('ELT040', 'Eletrônica de Potência', 4, 'OPT'),
       ('ELT042', 'Laboratório de Eletrônica de Potência', 3, 'OPT'),
       ('ELT043', 'Fontes de Alimentação CC e CA', 3, 'OPT'),
       ('ELT044', 'Teoria da Irradiação e Ondas Guiadas', 4, 'OPT'),
       ('ELT046', 'Antenas', 5, 'OPT'),
       ('ELT047', 'Comunicações Digitais', 4, 'OPT'),
       ('ELT048', 'Comunicações Móveis', 4, 'OPT'),
       ('ELT049', 'Comunicações Ópticas', 4, 'OPT'),
       ('ELT050', 'Microondas', 4, 'OPT'),
       ('ELT051', 'Propagação de Ondas de Rádio', 4, 'OPT'),
       ('ELT052', 'Redes de Telecomunicações', 5, 'OPT'),
       ('ELT115', 'Sistemas de Controle Não-Lineares', 2, 'OPT'),
       ('ENGx25', 'Estudos Pós-Graduação I', 4, 'OPT'),
       ('ENGx26', 'Estudos Pós-Graduação II', 4, 'OPT'),
       ('ENGx27', 'Modelagem e Simulação de Sistemas a Eventos Discretos', 4, 'OPT'),
       ('ENGx28', 'Programa Acadêmico de Graduação I', 1, 'OPT'),
       ('ENGx29', 'Programa Acadêmico de Graduação II', 1, 'OPT'),
       ('ENGx30', 'Programa de Monitoria I', 1, 'OPT'),
       ('ENGx31', 'Programa de Monitoria II', 1, 'OPT'),
       ('ENG017', 'Programa de Iniciação Científica I', 2, 'OPT'),
       ('ENG018', 'Programa de Iniciação Científica II', 1, 'OPT'),
       ('ENG019', 'Projeto Orientado I', 1, 'OPT'),
       ('ENG020', 'Projeto Orientado II', 1, 'OPT'),
       ('ENG021', 'Projeto de Extensão I', 1, 'OPT'),
       ('ENG022', 'Projeto de Extensão II', 1, 'OPT'),
       ('ENG024', 'Produção Científica I', 1, 'OPT'),
       ('ENG025', 'Produção Científica II', 1, 'OPT'),
       ('ENG026', 'Atividade a Distância I', 1, 'OPT'),
       ('ENG027', 'Atividade a Distância II', 1, 'OPT'),
       ('ENG028', 'Formação Livre I', 4, 'OPT'),
       ('ENG029', 'Formação Livre II', 4, 'OPT'),
       ('ENG102', 'Vivência Profissional Complementar', 2, 'OPT'),
       ('ENUx32', 'Fundamentos de Energia Nuclear', 4, 'OPT'),
       ('ENU005', 'Metodologia e Modelos de Planejamento Energético', 4, 'OPT'),
       ('EPD001', 'Organização Industrial para Engenharia', 4, 'OPT'),
       ('EPD034', 'Planejamento da Produção', 4, 'OPT'),
       ('EPD035', 'Sistema de Desenvolvimento do Produto', 4, 'OPT'),
       ('FIS091', 'Fundamentos da Teria da Relatividade', 2, 'OPT'),
       ('FISnn1', 'Fundamentos de Elasticidade e Hidrodinâmica', 2, 'OPT'),
       ('LEG601', 'Inglês Instrumental I', 4, 'OPT'),
       ('LEG602', 'Inglês Instrumental II', 4, 'OPT'),
       ('MAT118', 'Variáveis Complexa', 4, 'OPT'),
       ('aaax01', 'Inteligência Computacional', 4, 'OPT'),
       ('aaax02', 'Estudos Avançados', 4, 'OPT'),
('ELT095', 'Projetos com Amplificadores Operacionais e Circuitos Eletrônicos Analógicos', 3, 'OPT');


select * from disciplina