--
---- S I M U L A D O   1
--
---- Utilize o BD AEmpresa
--
--
--01 - Exiba todos os dados dos clientes da cidade de Buenos Aires em ordem crescente de nome.
--02 - Exiba todos os dados dos fornecedores do Japão em ordem decrescente de cargo.
--03 - Mostre o cargo e a quantidade de fornecedores por cargo.
--04 - Usando UNION mostre contato e cargo de todos os clientes da Alemanha e 
--05 - Usando UNION mostre contato e cargo de todos os clientes cujo cargo é Agente de vendas e 
--06 - Exiba descrição e preço dos 3 produtos mais caros.
--07 - Exiba descrição e preço dos 4 produtos mais baratos.
--08 - Exiba soma, média, maior valor e menor valor de todos os produtos da categoria 'Frutos do Mar'
--09 - Exiba todos os dados dos produtos da categoria bebidas, crie um campo aumentando o valor em 10%
--10 - Exiba todos os dados dos produtos da categoria condimentos, crie um campo diminuindo o valor em 20%
--11 - Exiba todos os dados dos pedidos feitos pelos clientes de cargo 'Proprietário'.
--12 - Mostre todos os dados dos clientes que compraram o produto 'Guaraná Fantástica'.
--13 - Usando conectivos (IN ou NOT IN) mostre os dados dos clientes que realizaram compras em setembro de 1997.
--14 - Usando conectivos (IN ou NOT IN)mostre os dados dos produtos que não foram comprados em abril de 1996.
--15 - Usando conectivos (IN ou NOT IN) Mostre o nome dos clientes que não compraram o produto 'chocolade'
--16 - Usando conectivos (IN ou NOT IN) mostre a descrição dos produtos comprados pelos clientes cujos nomes começam com A.
--17 - Crie a visão 'produtos_carnes' que mostre todos os dados dos produtos da categoria 'carnes/aves'.
--18 - Crie a visão 'pedidos_EUA' que mostre todos os pedidos feitos por clientes dos EUA.
--19 - Usando Join crie a visão 'pedidos_entregues_berlin_1996' que mostre todos os dados dos pedidos feitos por clientes de 'Berlin' e que foram entregues em 1996.
--20 - Usando Join crie a visão 'pedidos_descontinuados' que mostre o número dos pedidos que contiveram produtos descontinuados 
